#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use GitSplit\Commands\SplitConflictFileCommand;

$application = new Application();

// ... register commands
$application->add(new SplitConflictFileCommand());

$application->run();
